import { notFound } from "next/navigation";
import Link from "next/link";
import { getDashboard, verifyProductClaim } from "@confia/product-data";
export const dynamic = "force-dynamic";
export default async function Section({ params }: { params: Promise<{ section: string }> }) {
  const { section } = await params;
  if (section === "verification") {
    const { products } = getDashboard();
    return <div className="dashboard-page section-page"><p className="eyebrow">CLAIM-LEVEL REVIEW · MCP SHARED ENGINE</p><h1>Verification results</h1><p className="dashboard-lead">Scores are calculated by the same deterministic engine used by the MCP tools. Open any record to inspect the supporting evidence.</p><section className="grid verification-grid">{products.map(p => <article className="glass-panel" key={p.productId}><div className="verification-card-top"><span className={`state-badge ${p.verificationState}`}>{p.verificationState}</span><strong>{p.trustScore ?? "N/A"}<small> / 10</small></strong></div><h2><Link href={`/dashboard/products/${p.productId}`}>{p.name}</Link></h2><p>{p.reasons.map(r => `${r.claimKey}: ${r.status}`).join("; ") || "All required evidence is eligible."}</p><Link className="panel-link" href={`/dashboard/products/${p.productId}`}>View record ↗</Link></article>)}</section></div>;
  }
  if (section === "discrepancies") {
    const result = verifyProductClaim({ productId: "drill-001", claims: { priceMinor: 19999, currency: "USD" } });
    const item = result.results[0];
    return <div className="dashboard-page section-page"><p className="eyebrow">QUALITY CONTROL · DEMO</p><h1>Potential information discrepancy</h1><p className="dashboard-lead">A difference between records is a signal to investigate, not automatic proof of an AI hallucination.</p><article className="glass-panel discrepancy-card"><span className="state-badge warning">{item.status}</span><h2>Price claim needs a second look</h2><p>A supplied claim says <strong>$199.99 USD</strong> for drill-001, while the eligible catalog observation says <strong>{typeof item.observed === "number" ? `$${(item.observed / 100).toFixed(2)} USD` : "Unknown"}</strong>.</p><div className="comparison-row"><span>Submitted claim<strong>$199.99 USD</strong></span><span>Observed evidence<strong>{typeof item.observed === "number" ? `$${(item.observed / 100).toFixed(2)} USD` : "Unknown"}</strong></span><span>Difference<strong className="warning-text">Review</strong></span></div><p className="muted-note">{item.reason}</p><small>Observed: {item.observedAt}</small></article></div>;
  }
  if (section === "analytics") return <div className="dashboard-page section-page"><p className="eyebrow">VISIBILITY SIGNALS · DEMO</p><h1>Demonstration analytics</h1><p className="dashboard-lead">A preview of the metrics Confía can expose once product visibility data is connected.</p><section className="dashboard-metrics analytics-preview"><article className="metric-card"><span>AI visibility score</span><strong>78<small>/ 100</small></strong><p>+12% from last period</p></article><article className="metric-card"><span>Product mentions</span><strong>64<small>%</small></strong><p>Across tracked questions</p></article><article className="metric-card"><span>Freshness coverage</span><strong>92<small>%</small></strong><p>Evidence within window</p></article></section><article className="glass-panel analytics-empty"><span className="metric-icon purple">✦</span><h2>Connect your visibility source to unlock live reporting.</h2><p>Engagement analytics are not implemented in this synthetic demo. No live impressions, clicks, or conversions are being measured.</p></article></div>;
  notFound();
}
