import Link from "next/link";
import { getDashboard } from "@confia/product-data";
export const dynamic = "force-dynamic";
export default function Dashboard() {
  const data = getDashboard();
  const conflictingCount = data.products.filter((product) => product.verificationState === "conflicting").length;
  const staleCount = data.products.filter((product) => product.verificationState === "stale").length;
  const partialCount = data.products.filter((product) => product.verificationState === "partial").length;
  const coverage = Math.round((data.verifiedCount / data.products.length) * 100);
    return <div className="dashboard-page">
      <div className="dashboard-heading"><div><p className="eyebrow">SYNTHETIC BUSINESS DEMO <span className="live-pill"><span className="status-dot" /> Live data</span></p><h1>Your verification workspace</h1><p className="dashboard-lead">The same product records and scoring functions exposed to ChatGPT, organized for a faster daily review.</p></div><div className="heading-actions"><Link className="button button-muted" href="/dashboard/analytics">View analytics</Link><Link className="button" href="/dashboard/products">Explore catalog <span>↗</span></Link></div></div>
      <section className="dashboard-metrics"><article className="metric-card metric-card-feature"><div className="metric-label"><span className="metric-icon">◎</span><span>Catalog health</span><span className="trend-up">+8.2%</span></div><strong>{coverage}<small>%</small></strong><p>of products fully verified</p><div className="progress-track"><span style={{ width: `${coverage}%` }} /></div></article><article className="metric-card"><div className="metric-label"><span className="metric-icon purple">✦</span><span>Average Trust Score</span></div><strong>{data.averageTrustScore ?? "N/A"}<small>/ 10</small></strong><p>Across assessed products</p><span className="metric-foot">↑ 0.4 this revision</span></article><article className="metric-card"><div className="metric-label"><span className="metric-icon amber">!</span><span>Needs attention</span></div><strong>{conflictingCount + staleCount}<small> items</small></strong><p>Conflicts or stale evidence</p><Link className="metric-link" href="/dashboard/discrepancies">Review issues ↗</Link></article><article className="metric-card"><div className="metric-label"><span className="metric-icon blue">◷</span><span>Evidence freshness</span></div><strong>{Math.max(0, 100 - staleCount * 12)}<small>%</small></strong><p>Observations within window</p><span className="metric-foot">Last sync · 2h ago</span></article></section>
      <section className="dashboard-columns"><article className="glass-panel activity-panel"><div className="panel-heading"><div><p className="eyebrow">Workspace pulse</p><h2>Recent activity</h2></div><button className="icon-button" type="button" aria-label="More activity">•••</button></div><div className="activity-list"><div className="activity-item"><span className="activity-symbol green">✓</span><div><strong>Catalog revision published</strong><small>{data.catalogRevision}</small></div><time>2h ago</time></div><div className="activity-item"><span className="activity-symbol purple">✦</span><div><strong>Trust scores recalculated</strong><small>{data.products.length} product records evaluated</small></div><time>2h ago</time></div><div className="activity-item"><span className="activity-symbol amber">!</span><div><strong>{conflictingCount ? `${conflictingCount} conflicting record needs review` : "No conflicting records"}</strong><small>Keep discrepancies visible to AI shoppers</small></div><time>Today</time></div><div className="activity-item"><span className="activity-symbol blue">↗</span><div><strong>AI connection is ready</strong><small>Four read-only MCP tools available</small></div><time>Live</time></div></div><Link className="panel-link" href="/dashboard/products">Open product catalog <span>↗</span></Link></article><article className="glass-panel score-panel"><div className="panel-heading"><div><p className="eyebrow">Score distribution</p><h2>Information confidence</h2></div><span className="panel-period">Current</span></div><div className="score-visual"><div className="donut"><span>{data.averageTrustScore ?? "N/A"}<small>/10</small></span></div><div className="score-legend"><span><i className="legend-green" />Verified <strong>{data.verifiedCount}</strong></span><span><i className="legend-purple" />Partial <strong>{partialCount}</strong></span><span><i className="legend-amber" />Needs review <strong>{conflictingCount + staleCount}</strong></span></div></div><div className="score-note"><span>ⓘ</span> Trust Score reflects confidence in product information, not product quality.</div></article></section>
      <section className="quick-actions"><div><p className="eyebrow">Move faster</p><h2>What do you want to review?</h2></div><Link href="/dashboard/products" className="quick-action"><span className="quick-icon green">⌕</span><span><strong>Browse products</strong><small>Inspect every score and source</small></span><span>↗</span></Link><Link href="/dashboard/verification" className="quick-action"><span className="quick-icon purple">✦</span><span><strong>Review verification</strong><small>See claim-level evidence</small></span><span>↗</span></Link><Link href="/dashboard/discrepancies" className="quick-action"><span className="quick-icon amber">!</span><span><strong>Resolve discrepancies</strong><small>Compare supplied claims</small></span><span>↗</span></Link></section>
    </div>;
}
